package com.u2.wise.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseTeacher<M extends BaseTeacher<M>> extends Model<M> implements IBean {

		/**  */
		public void setId(java.lang.String id) {
			set("id", id);
		}
		/**  */
		public java.lang.String getId() {
			return get("id");
		}
		/**  */
		public void setName(java.lang.String name) {
			set("name", name);
		}
		/**  */
		public java.lang.String getName() {
			return get("name");
		}
		/**  */
		public void setPhone(java.lang.String phone) {
			set("phone", phone);
		}
		/**  */
		public java.lang.String getPhone() {
			return get("phone");
		}
		/**  */
		public void setSex(java.lang.Integer sex) {
			set("sex", sex);
		}
		/**  */
		public java.lang.Integer getSex() {
			return get("sex");
		}
		/**  */
		public void setClassType(java.lang.String classType) {
			set("class_type", classType);
		}
		/**  */
		public java.lang.String getClassType() {
			return get("class_type");
		}
		/**  */
		public void setRemark(java.lang.String remark) {
			set("remark", remark);
		}
		/**  */
		public java.lang.String getRemark() {
			return get("remark");
		}
		/**  */
		public void setCreateTime(java.util.Date createTime) {
			set("create_time", createTime);
		}
		/**  */
		public java.util.Date getCreateTime() {
			return get("create_time");
		}
		/**  */
		public void setDelFlag(java.lang.Long delFlag) {
			set("del_flag", delFlag);
		}
		/**  */
		public java.lang.Long getDelFlag() {
			return get("del_flag");
		}

}