package com.u2.wise.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCurriculum<M extends BaseCurriculum<M>> extends Model<M> implements IBean {

		/**  */
		public void setId(java.lang.String id) {
			set("id", id);
		}
		/**  */
		public java.lang.String getId() {
			return get("id");
		}
		/**  */
		public void setName(java.lang.String name) {
			set("name", name);
		}
		/**  */
		public java.lang.String getName() {
			return get("name");
		}
		/**  */
		public void setSubject(java.lang.String subject) {
			set("subject", subject);
		}
		/**  */
		public java.lang.String getSubject() {
			return get("subject");
		}
		/**  */
		public void setType(java.lang.Integer type) {
			set("type", type);
		}
		/**  */
		public java.lang.Integer getType() {
			return get("type");
		}
		/**  */
		public void setGrade(java.lang.String grade) {
			set("grade", grade);
		}
		/**  */
		public java.lang.String getGrade() {
			return get("grade");
		}
		/**  */
		public void setTeacherId(java.lang.String teacherId) {
			set("teacher_id", teacherId);
		}
		/**  */
		public java.lang.String getTeacherId() {
			return get("teacher_id");
		}
		/**  */
		public void setTeacherName(java.lang.String teacherName) {
			set("teacher_name", teacherName);
		}
		/**  */
		public java.lang.String getTeacherName() {
			return get("teacher_name");
		}
		/**  */
		public void setStartTime(java.util.Date startTime) {
			set("start_time", startTime);
		}
		/**  */
		public java.util.Date getStartTime() {
			return get("start_time");
		}
		/**  */
		public void setEndTime(java.util.Date endTime) {
			set("end_time", endTime);
		}
		/**  */
		public java.util.Date getEndTime() {
			return get("end_time");
		}
		/**  */
		public void setRemark(java.lang.String remark) {
			set("remark", remark);
		}
		/**  */
		public java.lang.String getRemark() {
			return get("remark");
		}
		/**  */
		public void setDelFlag(java.lang.Integer delFlag) {
			set("del_flag", delFlag);
		}
		/**  */
		public java.lang.Integer getDelFlag() {
			return get("del_flag");
		}

}