package com.u2.wise.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStudent<M extends BaseStudent<M>> extends Model<M> implements IBean {

		/**  */
		public void setId(java.lang.String id) {
			set("id", id);
		}
		/**  */
		public java.lang.String getId() {
			return get("id");
		}
		/**  */
		public void setName(java.lang.String name) {
			set("name", name);
		}
		/**  */
		public java.lang.String getName() {
			return get("name");
		}
		/**  */
		public void setAge(java.lang.Integer age) {
			set("age", age);
		}
		/**  */
		public java.lang.Integer getAge() {
			return get("age");
		}
		/**  */
		public void setSex(java.lang.Integer sex) {
			set("sex", sex);
		}
		/**  */
		public java.lang.Integer getSex() {
			return get("sex");
		}
		/**  */
		public void setCode(java.lang.String code) {
			set("code", code);
		}
		/**  */
		public java.lang.String getCode() {
			return get("code");
		}
		/**  */
		public void setParentName(java.lang.String parentName) {
			set("parent_name", parentName);
		}
		/**  */
		public java.lang.String getParentName() {
			return get("parent_name");
		}
		/**  */
		public void setParentInfo(java.lang.String parentInfo) {
			set("parent_info", parentInfo);
		}
		/**  */
		public java.lang.String getParentInfo() {
			return get("parent_info");
		}
		/**  */
		public void setCreateTime(java.util.Date createTime) {
			set("create_time", createTime);
		}
		/**  */
		public java.util.Date getCreateTime() {
			return get("create_time");
		}
		/**  */
		public void setStartTime(java.util.Date startTime) {
			set("start_time", startTime);
		}
		/**  */
		public java.util.Date getStartTime() {
			return get("start_time");
		}

}