package com.u2.wise.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseClassRecord<M extends BaseClassRecord<M>> extends Model<M> implements IBean {

		/**  */
		public void setId(java.lang.String id) {
			set("id", id);
		}
		/**  */
		public java.lang.String getId() {
			return get("id");
		}
		/**  */
		public void setCid(java.lang.String cid) {
			set("cid", cid);
		}
		/**  */
		public java.lang.String getCid() {
			return get("cid");
		}
		/**  */
		public void setRecordData(java.util.Date recordData) {
			set("record_data", recordData);
		}
		/**  */
		public java.util.Date getRecordData() {
			return get("record_data");
		}
		/**  */
		public void setStartTime(java.util.Date startTime) {
			set("start_time", startTime);
		}
		/**  */
		public java.util.Date getStartTime() {
			return get("start_time");
		}
		/**  */
		public void setEndTime(java.util.Date endTime) {
			set("end_time", endTime);
		}
		/**  */
		public java.util.Date getEndTime() {
			return get("end_time");
		}
		/**  */
		public void setClassHour(java.lang.Double classHour) {
			set("class_hour", classHour);
		}
		/**  */
		public java.lang.Double getClassHour() {
			return get("class_hour");
		}
		/**  */
		public void setRemark(java.lang.String remark) {
			set("remark", remark);
		}
		/**  */
		public java.lang.String getRemark() {
			return get("remark");
		}
		/**  */
		public void setDelFlag(java.lang.Integer delFlag) {
			set("del_flag", delFlag);
		}
		/**  */
		public java.lang.Integer getDelFlag() {
			return get("del_flag");
		}

}