package com.u2.wise.model.base;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseStudentPayment<M extends BaseStudentPayment<M>> extends Model<M> implements IBean {

		/**  */
		public void setId(java.lang.String id) {
			set("id", id);
		}
		/**  */
		public java.lang.String getId() {
			return get("id");
		}
		/**  */
		public void setStudentId(java.lang.String studentId) {
			set("student_id", studentId);
		}
		/**  */
		public java.lang.String getStudentId() {
			return get("student_id");
		}
		/**  */
		public void setAmount(java.lang.Long amount) {
			set("amount", amount);
		}
		/**  */
		public java.lang.Long getAmount() {
			return get("amount");
		}
		/**  */
		public void setPayDate(java.util.Date payDate) {
			set("pay_date", payDate);
		}
		/**  */
		public java.util.Date getPayDate() {
			return get("pay_date");
		}
		/**  */
		public void setRemark(java.lang.String remark) {
			set("remark", remark);
		}
		/**  */
		public java.lang.String getRemark() {
			return get("remark");
		}
		/**  */
		public void setDelFlag(java.lang.Integer delFlag) {
			set("del_flag", delFlag);
		}
		/**  */
		public java.lang.Integer getDelFlag() {
			return get("del_flag");
		}

}