package com.u2.wise.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("t_class_record", "id", ClassRecord.class);
		arp.addMapping("t_curriculum", "id", Curriculum.class);
		arp.addMapping("t_curriculum_config", "id", CurriculumConfig.class);
		arp.addMapping("t_curriculum_student", "id", CurriculumStudent.class);
		arp.addMapping("t_student", "id", Student.class);
		arp.addMapping("t_student_payment", "id", StudentPayment.class);
		arp.addMapping("t_teacher", "id", Teacher.class);
	}
}
