	#namespace("classRecord")
	#include("classRecord.sql")
	#end
	#namespace("curriculum")
	#include("curriculum.sql")
	#end
	#namespace("curriculumConfig")
	#include("curriculumConfig.sql")
	#end
	#namespace("curriculumStudent")
	#include("curriculumStudent.sql")
	#end
	#namespace("student")
	#include("student.sql")
	#end
	#namespace("studentPayment")
	#include("studentPayment.sql")
	#end
	#namespace("teacher")
	#include("teacher.sql")
	#end
